- name: Congigue docker in EC2 Instance
  hosts: all
  become: true
  connection: ssh
  tasks:
- name: Update EC2 instance
  command: sudo yum update
  
- name: Tnstall docker
  command: sudo tum install dockere-y
  become: yes
  become_user: root
  
- name: Start Docker service
  command: systemctl start docker
  become: yes
  become_user: root

  
  
  
  

  
